### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Timeslice42** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#1]
Would you please put a link to the post containing the documentation for this addon into the README.md file?

**Comment by Dream-Master** [comment]
Yes I will do tomorrow. When you go to the Minetweaker  page from Stan go to the wiki and than to Gregtech. There you find all information because I edit this page and add my code there.

**Comment by Timeslice42** [comment]
Thank you.

**Comment by Dream-Master** [comment]
The other machines I not add like the arc furnace will follow soon.

**Comment by Dream-Master** [comment]
Btw I collecting minetweaker scripts. Look at my repository lets Greg other mods if you like.

**Comment by Dream-Master** [comment]
So Wiki is done. Check it out and say to me if this is enough.
https://github.com/Dream-Master/Minetweaker-Gregtech-5-Addon/wiki

**Comment by Timeslice42** [comment]
Looks good to me. I only see one consistency/typo error: on the distillery it should probably read "(true = Recipe are hidden)" to be consistent with the phrasing on the other methods that can hide recipes.

I do have a question about the BBF. If the output liquid is always null, then why expose that parameter at all? Why not just have null passed internally?

**Comment by Dream-Master** [comment]
I look inside this

**Comment by Timeslice42** [comment]
Did you ever get a chance to look at the BBF?

**Comment by Dream-Master** [comment]
I don't know how I can fix it. My coding knowledge isn't that big. Will asking the coder in my team.

**Comment by Dream-Master** [comment]
@Timeslice42 
So finaly fix it with the Blast Furnace.
Version 0.7.5 is up to date but it need Gregtech 5.08.26 to work right.

**Comment by Timeslice42** [comment]
Thanks. :)
