### ISSUE TITLE
[1.4.0 beta] Broken handler for Mixer (problem with overriding of method?)

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#10]
Hello.
With GTTweaker 1.4.0 I can't add recipes for Mixer with fluids. For example, any of these recipes:
```
Mixer.addRecipe(<ThermalFoundation:material:42> * 16, null, [<ore:dustCopper>.firstItem * 11, <ore:dustSterlingSilver>.firstItem * 5], <liquid:redstone> * 4000, 1600, 8);
Mixer.addRecipe(<ThermalFoundation:material:43> * 4, null, [<ore:dustTin>.firstItem * 3, <ore:dustSilver>.firstItem], <liquid:glowstone> * 1000, 400, 8);
Mixer.addRecipe(<ThermalFoundation:material:44> * 4, null, [<ore:dustTin>.firstItem * 2, <ore:dustSilver>.firstItem, <ore:dustPlatinum>.firstItem], <liquid:ender> * 1000, 800, 8);
```
cause ```java.lang.Integer cannot be cast to net.minecraft.item.ItemStack```.

I guess, MineTweaker tries to run [this method](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Mixer.java#L50) instead of [that](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Mixer.java#L35).
Please, fix this problem.

And I sure, that these recipes are correct, because its *__worked properly__* on version 1.2.2.

// Also, fix mistake/typo in [logger output](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Mixer.java#L37) - Mixer != Lathe :smile: 

P. S. Sorry for my English. I'm from Russia.

**Comment by Dream-Master** [comment]
@OneEyeMaker 
1.4.0 is beta pushed by Techlone. Feel free to change code and send me a pull request.

**Comment by Techlone** [comment]
My bad. Missed output arg. See #11

**Comment by Dream-Master** [comment]
Thanks.

@OneEyeMaker 

Can you try again please.

**Comment by OneEyeMaker** [comment]
@Dream-Master 
I tested build 21 (from Jenkins).
Works fine:
http://imgur.com/ZrbwoqU
Thank you!
