### ISSUE TITLE
[1.4.0 beta] Weird things with FluidSolidifier recipes.

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#12]
Hello.
In version 1.4.0 GTTweaker adds FluidSolidifier recipes incorrectly:
1) All recipes doesn't contain output;
2) All recipes contain wrong amount of fluid (amount in script / 8);
3) In all recipes input doesn't get consumed, even if it should be.
Please, fix these problems.
Also, please, check all other handlers (for other GT machines) before publishing new (beta) version.

P. S. Sorry for my English. I'm from Russia.

**Comment by Techlone** [comment]
Собственно, для этого и нужен бета тест :)
Во FluidSolidifier я чот вообще намудрил, ладно, проверю остальное.

**Comment by Techlone** [comment]
@OneEyeMaker на счет п.2 и п.3 кинь скрипты.

**Comment by OneEyeMaker** [comment]
@Techlone 
```
FluidSolidifier.addRecipe(<ExtraUtilities:decorativeBlock1:1>, <ore:blockObsidian>.firstItem, <liquid:molten.enderium> * 144, 128, 64);
FluidSolidifier.addRecipe(<ExtraUtilities:decorativeBlock2:4>, <ExtraUtilities:decorativeBlock2:0>, <liquid:molten.gold> * 128, 128, 8);
```
// These scripts add recipes for Ender-Infused obsidian and Golden Glass from ExtraUtilities.

**Comment by OneEyeMaker** [comment]
// And these scripts on v1.2.2 work correctly.

**Comment by Techlone** [comment]
I can't test it now. See #13 
@Dream-Master do not close this issue because I didn't fix p.2... I think.
@OneEyeMaker на счет неверного значения количества жидкости - даже не знаю, в чем причина. Протестирую как только смогу.

**Comment by Dream-Master** [comment]
@OneEyeMaker  Try 1.4.1
