### ISSUE TITLE
Ordictionary issue

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#14]
A user __LEXX__  report this error.

ore dictionary
Not sure if it's bug or a feature, but when i add recipe into the machine and raw materials using ore dictionary (<ore:dustCopper> * 9), the recipe comes up, but without taking amount into calculation. Takes 1 instead of 9. But if i am using straight up name of the item (<gregtech:gt.metaitem.01:2345> * 9) - the amount is correct.

@Techlone any idea?

**Comment by Techlone** [comment]
Yeah, it's a bug. I'll look it up tomorrow. However, I think it's already fixed but not sure.

**Comment by Dream-Master** [comment]
Thanks

**Comment by Dream-Master** [comment]
I compile a version with the new code and the user __LEXX__  said it is fixed now.

**Comment by Techlone** [comment]
Nice :)

**Comment by Dream-Master** [comment]
Ok i close it now and reopen it when the problem not gone.
