### ISSUE TITLE
Broken handler for Plasma Arc Furnace.

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#15]
Hello!
The title says it all. Your handler for Plasma Arc Furnace is broken: it ignores output fluid at all and tries to cast ```FluidStack``` to ```int[]``` (=> ClassCastException).

My script for Plasma Arc Furnace:
```
PlasmaArcFurnace.addRecipe([<ore:ingotBedrockium>.firstItem * 9], <liquid:argon> * 1, <ore:blockBedrockium>, <liquid:plasma.argon> * 1, [10000], 55, 32);
PlasmaArcFurnace.addRecipe([<ore:ingotBedrockium>.firstItem * 9], <liquid:nitrogen> * 3, <ore:blockBedrockium>, <liquid:plasma.nitrogen> * 1, [10000], 55, 32);
```

I guess you just need to add ```i.nextFluid()``` between ```i.nextItemArr()``` and ```i.nextIntArr()```.

Also, you should have two methods for Plasma Arc Furnace - one with fluid output and one without it (GT5u has both methods of registration recipes for Plasma Arc Furnace - [first](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_RecipeAdder.java#L690) and [second](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_RecipeAdder.java#L706)).

Please, fix this problem.

**Comment by Dream-Master** [comment]
@Techlone 

Any idea here ?

**Comment by OneEyeMaker** [comment]
@Dream-Master 
I know about this rewrite (I'm using GTTweaker-1.4.1).

**Comment by Dream-Master** [comment]
@OneEyeMaker 
Is the old version without Ordict support working?
I using custom Arc Furnace recipe and for me it is working.

**Comment by OneEyeMaker** [comment]
@Dream-Master 
Arc Furnace != Plasma Arc Furnace. These ones are different machines and have diffenet handlers in GT and GTTweaker. (Arc Furnace recipes work properly, Plasma Arc Furnace doesn't).
And I didn't try to test this bug with older version of GTTweaker.

**Comment by Techlone** [comment]
>I guess you just need to add i.nextFluid() between i.nextItemArr() and i.nextIntArr().

Right.
>two methods for Plasma Arc Furnace

I added overload with null fluidOutput.
#16

**Comment by Dream-Master** [comment]
ok i add those code.

Thanks.
