### ISSUE TITLE
Gregtech 1.10[informative]

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#17]
there is now a stable build for gregtech if you would like to update this mod

**Comment by Dream-Master** [comment]
Not sure if and when.

**Comment by mightydanp** [comment]
Theres a chat community that is helping with gregtech you could always see if one of them is interested in helping on porting it for you. One of them has there own modpack so im sure there going to need this.

**Comment by mightydanp** [comment]
https://discord.gg/7qqsmX7

**Comment by Dream-Master** [comment]
@mightydanp I am part of his group all ready so long it exists. I am out of time atm. Moveing my Home in 1 week have to take care my familie. So if you want to push code you are welcome or ask @Techlone maybe he can help here.

**Comment by mightydanp** [comment]
Alright thank you @Dream-Master

**Comment by Dream-Master** [comment]
Why you close it. Let it open so long I found Time to add this.

**Comment by mightydanp** [comment]
sorry i was at work and i pressed the wrong button in a hurry

**Comment by mightydanp** [comment]
I believe I got 
Archengius to port it for you.

**Comment by Dream-Master** [comment]
Yea would be nice. I will open up an new 1.10 branch for him.

**Comment by DoughnutDev** [comment]
So I got a 1.10.2 version of mod to work. Not sure where to go from here. A few of the machines don't work yet but I think that is because of the GregTech mod itself.

**Comment by Dream-Master** [comment]
@DoughnutDev Make a pull rwquest here.

**Comment by DoughnutDev** [comment]
There you go. I hope I was helpful.
