### ISSUE TITLE
[Question] two outputs

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#22]
@Techlone 

I try yur build with my scripts but it not works. Why all the recipes have two outputs because the error i have show something null.(second output slot)

For Expample this line:
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/AlloySmelter.java#L33

or this:

https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Assembler.java#L47

So long i using my old version.(branch old)

**Comment by Techlone** [comment]
>with my scripts but it not works

What scripts? attach please
>(second output slot)

These machines (smelter & assembler) has one solid output. What's a problem?

**Comment by Dream-Master** [comment]
@Techlone Sure will send you the error log asap.

**Comment by Techlone** [comment]
Actual?

**Comment by Dream-Master** [comment]
Sorry forgot it already never using the oredict version in my pack. Now I am in Holidays and new Year back.

**Comment by Techlone** [comment]
Any news?

**Comment by Dream-Master** [comment]
@Techlone sadly not rn. But i will loock into it fror the next release of my Modpack. I let you know. And Thanks you take care here the issues.

**Comment by Techlone** [comment]
Reopen if needed
