### ISSUE TITLE
AssemblyLine.addRecipe don't work

### ISSUE THREAD

**Issue by dalekin** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#23]
Error with this log:
Error executing scripts_1925618841: java.lang.Integer cannot be cast to net.minecraft.item.ItemStack

for this script (example. I test adding assembly line recipes):
[test.txt](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/files/573795/test.txt)

gregtech-5.09.26
CraftTweaker-1.7.10-3.0.13
GTTweaker-1.7.10-1.4.3

**Comment by Dream-Master** [comment]
Did you make a full recipe example because this ins't valid.

`mods.gregtech.AssemblyLine.addRecipe(aResearchItem, 144000, aInputs, aFluidInputs, aOutput, 600, 6000);`

**Comment by dalekin** [comment]
Yes. I used the recipe in one line instead of the variables.
And I shared a recipe for certain variables only to realize that everything is in its place.
One line also give the error.
```
mods.gregtech.AssemblyLine.addRecipe(<minecraft:iron_chestplate>, 144000, [<IC2:itemPartAlloy> * 5, <minecraft:iron_chestplate>, <gregtech:gt.metaitem.01:17780> * 6], [<liquid:glue> * 144], <IC2:itemArmorAlloyChestplate>, 600, 6000);
```

**Comment by dalekin** [comment]
for example this also don't work
```
mods.gregtech.AssemblyLine.addRecipe(<minecraft:iron_chestplate>, 144000, [<IC2:itemPartAlloy>], [<liquid:glue>], <IC2:itemArmorAlloyChestplate>, 600, 6000);
```
[Client thread/INFO]: [CHAT] ERROR: Error executing test.zs: java.lang.Integer cannot be cast to net.minecraft.item.ItemStack

**Comment by Dream-Master** [comment]
@draknyte1 any idea?

**Comment by draknyte1** [comment]
Nope.. This addition I PR'd might not work AT ALL, as nobody tested it.

**Comment by Techlone** [comment]
Sorry about my magic with oredict. First argument in `AddMultipleRecipeAction` ctor is just description for logging.
Must be something like that
```
MineTweakerAPI.apply(new AddMultipleRecipeAction("Adding Assembly Line recipe for " + aOutput, aResearchItem, aResearchTime, aInputs, aFluidInputs, aOutput, aDuration, aEUt) {
```

**Comment by draknyte1** [comment]
I've still never tested this.. So if I did something wrong I've got no idea.. 

Haven't looked back at this PR since that day I made it over lunch.

**Comment by Dream-Master** [comment]
@draknyte1 , @Techlone 
Any idea how to fix it?

**Comment by Techlone** [comment]
@Dream-Master I said above how to fix it. I'll create a PR.

**Comment by Dream-Master** [comment]
Sorry be in Holidays atm. Will merge your pull request. Thanks
