### ISSUE TITLE
Chemical Reactor doesn't have EnergyUsage

### ISSUE THREAD

**Issue by ApokalypseStudios** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#24]
When making a recipe with the Chemical Reactor, it doesn't have a EnergyUsage field.
Every recipe with the Chemical Reactor will be at 32 eu/tick.

**Comment by Dream-Master** [comment]
Old branch have it using version 1.1.1 but you dont have oredict support here.

http://forum.industrial-craft.net/index.php?page=Attachment&attachmentID=6304&h=03d86d350827be4300aec08ec603106b9cc31d24

https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/old/src/main/java/gttweaker/mods/gregtech/ChemicalReactor.java
