### ISSUE TITLE
[Question] How remove machine recipes

### ISSUE THREAD

**Issue by ApokalypseStudios** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#27]
Hi! I'm using this mod for fixing some bugs in my modpack.
I changed some recipes but I don't know how to erase some existing recipes (for example: deuterium to tritium in centrifuge doesn't work if Mekanism is in the modpack) for only keeping my own recipes.

**Comment by Techlone** [comment]
Open Recipes.cfg in GT's config folder. Find machine section and line with output of needed recipe. Set a number after equals sign to zero.

**Comment by ApokalypseStudios** [comment]
I don't mean for disabling any machine. (sorry for my bad english)
I mean that disabling this recipe, for example:
In Centrifuge, you can turn 16 Deuterium into 4 Tritium (default recipe in Gregtech) at 80 EU/tick in 16 ticks

**Comment by Techlone** [comment]
You need find machine section to determine recipe to be deleted. For your example you need find `centrifuge` section. There are curly brackets. After that find `I:deuterium_160=160` and replace with `I:deuterium_160=0`. Sometimes name of line is input ingredient sometimes it's output. Just try something and check it in the game.
What is your language?

**Comment by Dream-Master** [comment]
can i clode this?

**Comment by Techlone** [comment]
it seems only you can)

**Comment by Dream-Master** [comment]
K
