### ISSUE TITLE
[Question]Will there be a GT6Tweaker?

### ISSUE THREAD

**Issue by Ordpus** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#28]
Because I saw that you said you will use an advanced API instead of reflection to write a GT6Tweaker in the forum....

**Comment by Dream-Master** [comment]
I seen some minetweaker Gt 6 addon in the ic2 Forum. I not planning to add gt6 support. @techlone is it possible add gt6 compatibility easy to the mod?

**Comment by Techlone** [comment]
I don't know GT6's API. Maybe 'yes' maybe 'no'.
I will see dev version of GT6 and answer later.

**Comment by Dream-Master** [comment]
Ok

**Comment by Techlone** [comment]
I looked GT6 and didn't understand adding of recipes
I need more time or help)

**Comment by Dream-Master** [comment]
Ok when I am back at 1.1.17 I can look into it.

**Comment by Techlone** [comment]
Found it. So, GTTweaker for GT6 will be.
But I think it should be another project cuz now it's Minetweaker-**Gregtech-5**-Addon
A switching between GTT for 5.09 and GTT for 5.10 is a pain and I don't want add a branch for GT6 (and GT6 for 1.10/1.11 in the future).

**Comment by Invincible92** [comment]
I'm sorry to ask, but is there any news about the GT6 version? The mod that currently exists (MTUtils) hasn't been updated from a while (since March) and the methods do not function correctly.

**Comment by Dream-Master** [comment]
@Invincible92 best Chance you had write a small custom mod and add recipes via java and gt6 Api. Not too complicated I guess.

**Comment by Techlone** [comment]
If MTUtils already does GTTweaker work for GT6 I think it will be better to develop MTUtils further.
@LionZXY is an author of MTUtils right? Hey @LionZXY will you update your mod?

**Comment by LionZXY** [comment]
Oh. Can you describe what i must do in issue? 
https://github.com/LionZXY/MTUtils/issues

**Comment by Techlone** [comment]
@LionZXY well I don't exactly what you should implement but @Invincible92 said `the methods do not function correctly`
@Invincible92 so if you have some additions or bug reports for MTUtils go to the its bug tracker.

As a result I suggest don't do GTTweaker for GT 6 cuz [it already exists](https://github.com/LionZXY/MTUtil).
Closed.

**Comment by Dream-Master** [comment]
https://github.com/LionZXY/MTUtils

**Comment by Techlone** [comment]
fixed :)
