### ISSUE TITLE
[Question]If I want use GTtweaker I must use Crafttweaker?

### ISSUE THREAD

**Issue by BurovB** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#29]

**Comment by Techlone** [comment]
Ты можешь использовать или майнтвикер или крафттвикер, главное для 1.7.10

**Comment by BurovB** [comment]
Но вы же делаете версию 1.10.2?

**Comment by Techlone** [comment]
Версии для 1.10, так же как и для ГТ6, пока нет. Только ГТ5 и только 1.7.10

**Comment by BurovB** [comment]
Я имею ввиду что у вас в разделе "Code", если посмотреть меню "Brach", видно что вы разрабатываете 1.10.2 версию.

**Comment by Dream-Master** [comment]
Sorry I don't speak, read or understand russian.

**Comment by Techlone** [comment]
@Dream-Master don't worry, I deal with him.
@BurovB я ответил на твой первоначальный вопрос? Думаю да, закрывай задачу.
Еще раз, чтобы использовать гттвикер можешь использовать или майнтвикер или крафттвикер, без разницы.
