### ISSUE TITLE
GT Tweaker for 1.10.2

### ISSUE THREAD

**Issue by braeven** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#30]
Just like I was asked to:
Don't forget to build/test the GT-Tweaker version for the 1.10.2 version of GT 5U

**Comment by Dream-Master** [comment]
k will do tomorrow hopfully.

**Comment by Techlone** [comment]
GT5U for 1.10 is very unstable. I suggest wait for the stable GT's release.

**Comment by Techlone** [comment]
GTTweaker 1.10 works but JEI still doesn't show script's recipes (see #32). I close this.
@braeven if you still have any questions/suggestions/troubles open new issue.
