### ISSUE TITLE
trouble porting over recipes

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#31]
im getting this error you might have changed it from the but im getting this.

log
http://pastebin.com/JA1ZW8Ya

script
http://pastebin.com/WKbBU5Z8

**Comment by Dream-Master** [comment]
You need GTTweaker for it.

**Comment by Dream-Master** [comment]
@mightydanp I got very spare info from you.

More infos please!

What version of Minetweaker /Crafttweaker you are using?
What version of GTTweaker you are using?
What version of Ender io und Gregtech you are using?

**Comment by mightydanp** [comment]
CraftTweaker-1.10.2-3.0.17
GTTweaker1.10 latest in your github

im just having problems with adding recipes to the gregtech machines.
EnderIO-1.10.2-3.1.161
gregtech-5.10.34

.sorry for the bit of info i was ready to go to bed when i wrote this

**Comment by Techlone** [comment]
```
// --- Pulsating Crystal
Assembler.addRecipe(<enderio:itemMaterial:5>, <minecraft:diamond>, <ore:nuggetPulsatingIron> * 8, 600, 120);
 
// --- Vibrant Crystal
Assembler.addRecipe(<enderio:itemMaterial:6>, <minecraft:emerald>, <ore:nuggetVibrantAlloy> * 8, 600, 120);
```
GTTweaker 1.10 hasn't ore dict support. I don't know why.

**Comment by Dream-Master** [comment]
@techlone maybe you can add it to 1.1.0

**Comment by Techlone** [comment]
@DoughnutDev made port to 1.10 and he returned 'not ore dict' version of codebase
Let @DoughnutDev comment on it. I won't do unnecessary actions

**Comment by Dream-Master** [comment]
ok

**Comment by Dream-Master** [comment]
@DoughnutDev,

**Comment by mightydanp** [comment]
Ah no ore dictionary yet ? That actualy really sucks

**Comment by DoughnutDev** [comment]
@Techlone Where am I returning 'not ore dict'? Also this might just need an update with CraftTweaker and GregTech sense I ported this awhile ago.

**Comment by Techlone** [comment]
@DoughnutDev I really can't understand what you did here
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/commit/70cd47d09f84f19c57d25b592d6707d14100cba6

**Comment by DoughnutDev** [comment]
You know what @Techlone it looks like the push to the GitHub repository messed up because I have the oredict stuff on my PC. I will fix it later.

**Comment by mightydanp** [comment]
even if i changed the recipe to a non ore dictionary one they still do not work at all >.>

**Comment by Techlone** [comment]
Log again please

**Comment by mightydanp** [comment]
http://pastebin.com/10DCnEqf
minetweaker log

new script
http://pastebin.com/sFsWjaER

**Comment by Techlone** [comment]
>// --- Pulsating Crystal
Assembler.addRecipe(<enderio:itemMaterial:5>, <minecraft:diamond>, <gregtech:gt.metaitem.01:9204> * 8, 600, 120);

>INFO: Adding assembler recipe for <enderio:itemMaterial:5>

It should be fine. Do you sure that script not works? Try to find and remove (if it exist) line in `config/GregTech/Recipes.cfg` in `assembling` section with its recipe output.
I can't reproduce bug right now.

**Comment by mightydanp** [comment]
i just tested the recipe in game. nothing happens. It does not try to make the recipe at all

**Comment by mightydanp** [comment]
ive done more testing. It needs to be updated with jei support. the recipes work but cannot see them.

**Comment by DoughnutDev** [comment]
@Techlone Okay sorry it took so long but I am creating a pull request now and I just updated the libs and everything.

**Comment by Techlone** [comment]
>the recipes work but cannot see them

close

**Comment by JasonMcRay** [comment]
In my opinion there is no need to have a direct oredictionary support in machines. All you need is just a loop to iterate through the items in oredictionary.
Example:
```
for item in <ore:nuggetPulsatingIron>.items {
   Assembler.addRecipe(<enderio:itemMaterial:5>, <minecraft:diamond>, item * 8, 600, 120);
}
```

This will loop through the nuggetPusatingIron oredictionary and for each item in it it will add a recipe.

Also you can go little bit more indepth with multiple oredicts:
```
for nugget in <ore:nuggetPulsatingIron>.items {
  for diamond in <ore:gemDiamond>.items {
   Assembler.addRecipe(<enderio:itemMaterial:5>, diamond, nugget * 8, 600, 120);
 }
}
```

This will loop through both oredictionaries for diamond and Pulsating Iron nugget and add all possible recipes.

**Comment by Techlone** [comment]
@JasonMcRay 
Exactly this I made. Look at https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/1.10/src/main/java/gttweaker/mods/gregtech/AddMultipleRecipeAction.java

**Comment by Techlone** [comment]
Oh misunderstood...
What do you mean "there is no need to have a direct oredictionary support in machines"?
