### ISSUE TITLE
JEI Support

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#32]
Recipes dont show up in jei. Just a reminder ;).

**Comment by Dream-Master** [comment]
Never worked with MC 1.10. Need help here @Techlone

**Comment by Techlone** [comment]
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/issues/31#issuecomment-275538094

**Comment by Techlone** [comment]
@DoughnutDev push your local commits please.
After that we can talk about 1.10

**Comment by JasonMcRay** [comment]
@Techlone Sorry for tagging you, but just curious if there is anything that is being done with fix for JEI in 1.10 . I started fully my work on Infitech for 1.10 and it is bit annoying to not see the recipes in JEI. The recipes work, just not show up. I was taking a look at what Modtweaker did to fix that and i found that they did this: https://github.com/jaredlll08/ModTweaker/commit/94d69f8ba54a712912ccdec3f729c1175c51763c for embers mod support. I did a cleanup, because they moved couple lines over and found they added this

```
 @Override
        public void apply() {
            super.apply();
            successful.forEach((stack, recipe) -> {
                MineTweakerAPI.getIjeiRecipeRegistry().addRecipe(new MeltingRecipeWrapper(recipe));
            });
        }
        
        @Override
        public void undo() {
            super.undo();
            successful.forEach((stack, recipe) -> {
                MineTweakerAPI.getIjeiRecipeRegistry().removeRecipe(new MeltingRecipeWrapper(recipe));
            });
        }
```

I would try to make something like that in Gttweaker, but I am no modder, so I would probably get lost completely.

**Comment by Techlone** [comment]
@JasonMcRay thanx maybe it will help.
But i say it again - GT 1.10 is unstable.
Do we really need to do something with GTTweaker 1.10 right now?

**Comment by JasonMcRay** [comment]
I personally didn't had any hard issues with GT 1.10 so far. It is bit glitchy, true (maybe more than a "bit") but from my perspective I prefer working alongside the development. The best thing that mod devs can have are testers. And making a pack definitely helps iron out some bugs and giving out feedback.

So even with unstable mods, you can just work on stuff. I feel it is much better to start working on something ASAP and taking smaller steps than be rushed when the mod gets stable and ppl will start requesting "immediate" update and get overwhelmed.

**Comment by DoughnutDev** [comment]
@JasonMcRay I will look into adding that in the code tonight that might actually help fix it because right now the  recipes adding all works but you just can't view it.

**Comment by JasonMcRay** [comment]
@DoughnutDev Any progress on this? :) I would really love to be able to get InfiTech out fairly soon, but with this I cannot even push it to alpha testing, because of it :)

**Comment by Techlone** [comment]
Now we have a problem with it. To tell the truth I don't know how to get a just added GT's recipe in code and therefore I can't add recipes in the runtime. Maybe on the weekend I'll look it again and try to resolve it.

**Comment by Techlone** [comment]
Also my opinion is that GT should add its recipes into JEI by itself
@Blood-Asp

**Comment by Techlone** [comment]
Not actual
