### ISSUE TITLE
[Suggestion/Idea] Adding support for GT++ machines

### ISSUE THREAD

**Issue by Invincible92** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#38]
Hi there

I'm opening this issue to know if it would be possible to add Minetweaker support (or something like that) to GT++, so we can add/modify recipes to our hearts content in its machines.

**Comment by Techlone** [comment]
I guess it's possible
summon @draknyte1

**Comment by draknyte1** [comment]
What for?

**Comment by Techlone** [comment]
Is it possible?

**Comment by draknyte1** [comment]
I assume so?
I have no idea how GTTweaker works, so I don't see why not.. I use the gt API or extended versions of the classes I need.

**Comment by Techlone** [comment]
Can you tell me please where is this 'extended versions of the classes'?

**Comment by draknyte1** [comment]
Half my mod?
I extend many things, in many places..

What explicitly do you need to implement support? All machine recipes use the same code and classes gt does.

**Comment by Techlone** [comment]
Specifically, I want to see how you add recipes for GT++ machines

**Comment by Techlone** [comment]
Well I did it. @Dream-Master now you can make a release
And yes I know we need add wiki... ASAP

---
###### Any bugs possible

**Comment by Dream-Master** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:GregTech_Support

So i need to add the new content here.

**Comment by Techlone** [comment]
```
Alkalus
I'd prefer fission fuel didn't have a recipe adder via GTTweaker

Techlone
why?

Alkalus
Because it ruins realism.. any fuels that can exist for the LFTR already do...
I don't want extra junk fuels being an option because the LFTR won't support them..
It isn't effected by the recipe adder, its fuel usages are hard coded.
There 'is' a map but it's for nei purposes.

Techlone
"any fuels that can exist for the LFTR already do"
not in minecraft especially with magic mods
"its fuel usages are hard coded"
just saw it
weeeell it's not my problem it's your mod and you can do it like you want i just used your API

Alkalus
No. LFTRs won't get magic fuels.
There is 0 reason to support the fission fuel processing plant in GTTweaker
This is my polite request to remove any compatibility for it.
```
I should remove `addLFTRRecipe` and `addFissionFuel`. They are not affected on the real LFTR behavior; just add NEI screen.

**Comment by Techlone** [comment]
Done.

**Comment by Invincible92** [comment]
Sorry about the delay in answering, but I had a lot of experimental data to deal with from the lab. 

Yes, the machines to which support would have to be added (as you did before this reply) would be the Blast Alloy Smelter, the Coke Oven, the Chemical Dehydrator and the Matter Fabricator.
