### ISSUE TITLE
The Gregtech Assembling machine now has 6 item inputs

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#39]
Will this mod get an update to support all six inputs for the ordinary Assembler?

**Comment by Dream-Master** [comment]
@Ethryan Yes you can now add Assembler recipe with 6 items and one fluid.

**Comment by Dream-Master** [comment]
And this mod is Gregtech or did i not undertsand the Quiestion? @Ethryan

**Comment by Ethryan** [comment]
problem is i can't get it to work with in New Horizons when i try

**Comment by Dream-Master** [comment]
Oh no this is not added yet. I can add it via code not via minetweaker. But me or Technolone can implement ist when the version is ready.

**Comment by Techlone** [comment]
This increasing of assembler inputs is on a PR stage - https://github.com/Blood-Asp/GT5-Unofficial/pull/1100.
When GT released with this PR I will add a new method for 6 inputs or even an array of inputs like it's done for CircuitAssembler.

**Comment by Dream-Master** [comment]
@Techlone thanks in advance

**Comment by Ethryan** [comment]
I spent a few hours going over the code of this addon, but when i entered the [GTTweaker.java](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/GTTweaker.java) file, i couldn't find the [CircuitAssembler.class](https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/CircuitAssembler.java) in the list.  Is it missing or just not needed?

Just curious since all other machines seems to be in this file.

**Comment by Techlone** [comment]
Damn, true.
All machines added in recent versions have been not registered. *facepalm*
Fixing...

**Comment by Techlone** [comment]
Done.
Also we found out this bugs only now. Nobody uses new GTTweaker features -_-

**Comment by Ethryan** [comment]
Any news on the array update for this plugin?

**Comment by Techlone** [comment]
@Ethryan GT 31 is still at the `pre` stage. GT 30 doesn't have the assembler with six inputs.

**Comment by Dream-Master** [comment]
The mixer have now 6 slots too so more stuff to do :)

**Comment by Techlone** [comment]
Well maybe an using the pre versions is not too bad.
Wait for the weekend.

**Comment by Dream-Master** [comment]
sure

**Comment by Techlone** [comment]
To add a recipe that uses more than two slots write this
```
mods.gregtech.Assembler.addRecipe(output, [input1, input2, etc], fluidInput, durationTicks, euPerTick)
```
`fluidInput` can be null
