### ISSUE TITLE
Pulverizer not accepting ore dictionary ingredient

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#4]
```Javascript
Pulverizer.addRecipe([<gregtech:gt.metaitem.01:2809> * 6, <gregtech:gt.metaitem.01:2809>], <ore:logWood>, [10000, 8000], 400, 2);
```
Cause error
```
ERROR: Not an ingredient with a single item: <ore:logWood>
ERROR: Error executing gregtech.zs: [Lminetweaker.api.item.IIngredient; cannot be cast to [Lminetweaker.api.item.IItemStack;
```

I think here you need to iterate the oreDictionary for each itemStack.
This would work in pure Zenscript
```javascript
for logWood in <ore:logWood>.items {
  Pulverizer.addRecipe([<gregtech:gt.metaitem.01:2809> * 6, <gregtech:gt.metaitem.01:2809>], logWood, [10000, 8000], 400, 2);
}
```
That you could do internally for machines requesting an IItemStack as input.

**Comment by leagris** [comment]
Same issue with Pyrolyse Oven. Casting does not work and it is not happy with multiple item entries in ore-dictionary logWood.

**Comment by Dream-Master** [comment]
yes need to fixe it.

**Comment by leagris** [comment]
Well, it is not allowed to output an ingredient or an ore dictionary entry.
Output must be an IItemStack
       private final IIngredient output;

**Comment by Dream-Master** [comment]
sure you right. Have to fix it tomorrow.

**Comment by Dream-Master** [comment]
Dont like when things not working. 

@leagris 

Try this version please.

**Comment by Techlone** [comment]
It not will be works correctly because `getItemStack` ([link](https://github.com/stanhebben/MineTweaker3/blob/master/MineTweaker3-MC1710-Main/src/main/java/minetweaker/api/minecraft/MineTweakerMC.java#L92)) returns a zero indexed items.
You need to iterate by the each input in the each machine class... a big and routine work. Maybe some wrapper or something else can helps. I don't have an idea how to simplify it.

**Comment by leagris** [comment]
You should take a look at this example iterating IItemStack list from IIngredient in AddRecipeAction
http://www.programcreek.com/java-api-examples/index.php?source_dir=ModularArmour-master/src/main/java/chbachman/armour/register/MineTweaker.java

Well, since these are lists, you could use Iterators instead of for loop.
You also need to imbricate as much loop/iteration as there are input IIngredients.

**Comment by Dream-Master** [comment]
Maybe you can help me or push some code changes if you want. I am not a Java expert so need help here.

**Comment by Techlone** [comment]
ASAP
Now I'm trying to realize another idea for GTTweaker. Pull request is coming soon.

**Comment by Dream-Master** [comment]
Thanks.

**Comment by Dream-Master** [comment]
@Techlone 
Any new here ?

**Comment by Techlone** [comment]
@Dream-Master
I relaxed on the weekend. I'll be back soon.

**Comment by Dream-Master** [comment]
no rush ;)

**Comment by Dream-Master** [comment]
@Techlone 
Any news?

**Comment by Dream-Master** [comment]
Try new Beta 1.4 Version and reporte here if any one find bugs.

**Comment by Dream-Master** [comment]
try 1.4.1.
