### ISSUE TITLE
Circuit Assembler

### ISSUE THREAD

**Issue by MineWitherMC** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#40]
Whenever I create circuit assembler recipes it says that input item is minetweaker.api.item.IIngredient and cannot be cast to net.minecraft.item.ItemStack. Example:
`mods.gregtech.CircuitAssembler.addRecipe(<gregtech:gt.metaitem.03:32035>, [
	<gregtech:gt.metaitem.01:2324>, <gregtech:gt.blockmetal6:7>
], <liquid:argon> * 1000, 100, 100);`
Output:
`ERROR: Error executing script.zs: [Lminetweaker.api.item.IIngredient; cannot be cast to [Lnet.minecraft.item.ItemStack;`
GTTweaker built from source from this repository after last commit, GT5U .31 also built from source after chem. update (if it's important)
Upd. Possible fix: change IIngredient argument to IItemStack in addRecipe methods.

**Comment by Techlone** [comment]
>Possible fix: change IIngredient argument to IItemStack in addRecipe methods.

Nope. The bug is deeper. Sorry but can't fix it right now.

**Comment by Techlone** [comment]
Fixed.
