### ISSUE TITLE
Can't REMOVE the recipes

### ISSUE THREAD

**Issue by YoungGT** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#41]
Hello. I'm a modpack author. When I was editing a modpack with GTTweaker,I found GTTweaker couldn't remove GregTech's recipes.It doesn't work. So I went to the MineTweaker Wiki for help. It says "Each of these handlers can have recipes added or **removed**",but I found NOTHING about removing recipes given. Everything is about adding.I have already looked through GTNH's scripts.So can you create a tutorial ( or edit the wiki ) to tell us how to remove? Thank you.

**Comment by YoungGT** [comment]
I'm sorry that GregTech can remove recipes by itself,sorry to have delayed your time.You can close it now.

**Comment by Techlone** [comment]
You can change gregtech\Recipes.cfg file. It contains almost all recipes. Find out a machine section then an output of recipe that you want to remove in this machine section and set this value to zero.
