### ISSUE TITLE
GT Tweaker Uses Old IC2 Compressor(and Other Old Machines?)

### ISSUE THREAD

**Issue by MoXiaoFreak** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#43]
I've reported this in your another repo.

[Here](https://github.com/Dream-Master/Mods-Get-Gregged/issues/16#)

And that causes some items **uncraftable** in GTNH modpack.
Having Fixed yet?

**Comment by Techlone** [comment]
GT Tweaker doesn't support IC2 machines directly (`mods.ic2.Compressor`). GTT uses GT's API.
