### ISSUE TITLE
Machine update methods

### ISSUE THREAD

**Issue by Invincible92** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#44]
Hi there

The following machines seem to need an update in the method of adding recipes:

- Chemical Reactor (now supports 2 item outputs + 1 fluid output; before 1 item output + 1 fluid output)

- Oil Cracking Unit (accepts another fluid to perform the cracking process besides the oil input, as steam or hydrogen, for example)

- Bricked Blast Furnace (seems that with @JohannesGaessler update, these recipes are no longer hard-coded, maybe he can explain a little bit more this part).

- Distillation tower (now has 12 outputs possible: 1 for items, 11 for fluids)

**Comment by Dream-Master** [comment]
I not realy developing on this mod anymore. If somone maje a pull request I will merge it.

**Comment by Techlone** [comment]
@Invincible92 which version of GT? 32pre?

**Comment by Dream-Master** [comment]
@Techlone use lastes source https://github.com/GTNewHorizons/GT5-Unofficial

**Comment by Invincible92** [comment]
@Techlone I'm using .32pre3, but this changes seem to be added since the .32 release. Also, I opened an issue in the GT5u GitHub about the functionality of the EBF with a fluid output hatch, so it seems that the fluid output can be tweaked too, so it could be another one to add to the list. 

I leave here the conversation link of the GT5u issue: https://github.com/Blood-Asp/GT5-Unofficial/issues/1400

**Comment by Techlone** [comment]
@Invincible92 test it if you can please, changes you can see here https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/commit/1df5e81d317bfdbb61a390576154f2d09f497dda
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/releases/tag/1.7.0
If all will be fine close the issue

**Comment by Techlone** [comment]
Out of date

**Comment by Invincible92** [comment]
Hi there

I'm truly sorry to bring this, but could it be possible to add, as the final update version of GTTweaker for 1.7.10, these 2 methods?

-  Large Chemical Reactor support (nowadays there is no method for adding a recipe)

- Single-block Distillery item output (some recipes include an item as output)

There is a lot of people that still use the GT5u version of GT (instead of using the available 1.12 version) and I was wondering if these 2 updates could be made.

Thank you in advance and happy New Year.

**Comment by Dream-Master** [comment]
This item output is only happend in code and very hacky so i cant give support for it.

The LCR can be added i guess. Not sure if i can do it but i will try.
