### ISSUE TITLE
Can not register assemble recipe that uses 3 slot or more than.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#46]
I tried to add a recipe to assembler that use 3 slot but I could not.
Environment:GT New Horizon ver2.0.6.0, GregTech 5.09.33.03, GTTweaker-1.7.10-1.7.0

**Comment by Techlone** [comment]
You have to pass an array https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/master/src/main/java/gttweaker/mods/gregtech/machines/Assembler.java#L47
`addRecipe(<out>, [<in1>, <in2>, <in3>, <in4>], ...)`
