### ISSUE TITLE
[Blast Furnace] Recipes do not work

### ISSUE THREAD

**Issue by UnlimatedStone9** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#47]
Hey there, I was having an issue with the blast furnace, I created recipes for the blast furnace which did in fact display in NEI however the recipes themselves do not appear to work

This is an example of one recipe

mods.gregtech.BlastFurnace.addRecipe([<terrafirmacraft:item.Wrought Iron Ingot>], null, [<tfcm:item.IronDust> * 10], 2000, 1, 10);

I also tried to use this one here requiring oxygen however it too did not appear to work

mods.gregtech.BlastFurnace.addRecipe([<terrafirmacraft:item.Wrought Iron Ingot>], <liquid:oxygen> * 1000, [<tfcm:item.IronDust> * 10], 2000, 1, 10);

I could use your help, thanks!              -UnlimatedStone9

**Comment by Dream-Master** [comment]
recipes with duplicate material use in another recipe wont work. Why not add a control circuit that not get consumed. I add a bunch of recipes with a controlcircuit * 0

**Comment by UnlimatedStone9** [comment]
I assume you mean because the material I have set as the input is already used as an input it won't add my recipe?
I don't believe all of the recipes I tried were in fact used already but I'll give you the benefit of the doubt because of oredictionaries

Could you present an example of a recipe using a controlcircuit? I'm not entirely sure what you mean

**Comment by UnlimatedStone9** [comment]
Oh I think I know what you mean, if there is only one input or output add an * 0 or * 1 for the item, so like
<terrafirmacraft:item.Wrought Iron Ingot> * 1   ???

**Comment by Dream-Master** [comment]
no if it is 1 let it like it is if it be 0 it will not consumed.

**Comment by Dream-Master** [comment]
and yes allready used items in input slot can't be used again. Use two items like the iron and a not consumed circuit.

**Comment by UnlimatedStone9** [comment]
So the circuit is an item that has not been used in a blast furnace recipe at all?

**Comment by UnlimatedStone9** [comment]
If so that is fine, I will look into it again, perhaps my items are used in a recipe already, thanks!

**Comment by UnlimatedStone9** [comment]
Regardless of what I try to do I cannot add any recipes to the blast furnace

**Comment by UnlimatedStone9** [comment]
Hey there Dream-Master, sorry to bother you again but I'm still having issues adding recipes to the blast furnace in "GregTech 5 Unofficial, 0.9.031, 1.7.10"

I have tried to use this recipe here:

mods.gregtech.BlastFurnace.addRecipe([<terrafirmacraft:item.HC Steel Ingot>, <gregtech:gt.metaitem.01:815>, <gregtech:gt.integrated_circuit> * 0], <liquid:oxygen> * 1000, [<terrafirmacraft:item.Pig Iron Ingot>], 100, 1, 1000000);

With the * 0 circuit as you suggested, I have placed the HC Steel Ingot into the Electrical Blast Furnace multiblock and cannot get the multiblock to consume the steel and process it into the output desired, Nor can I do this for the Bronze Plated or Bricked Blast Furnaces, however with testing I was able to get some default GregTech recipes to work, such as Aluminium dust into an ingot, so I know I have not set the machines up incorrectly

I was curious to know if you had any idea what could have caused this to not work?
