### ISSUE TITLE
Pyrolyse Oven Recipes

### ISSUE THREAD

**Issue by UnlimatedStone9** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#49]
I cannot seem to get any Pyrolyse Oven recipes to work as I want, they don't work and I don't understand why
This is the best I could come up with as recipes, based on the template on GitHub but it doesn't work, could you help me?

mods.gregtech.PyrolyseOven.addRecipe([<terrafirmacraft:item.coal:1> * 2, <liquid:creosote> * 1000], <gregtech:gt.integrated_circuit>, [<advancedRocketry:tile.charcoallog>, <liquid:freshwater> * 1000, 200, 5]);

**Comment by UnlimatedStone9** [comment]
A snipping of the recipe because GitHub likes to hide <>
![image](https://user-images.githubusercontent.com/40124890/58034541-b5bfec00-7b1e-11e9-86de-05279a81ac4d.png)

**Comment by Pilad** [comment]
mods.gregtech.PyrolyseOven.addRecipe(<minecraft:coal:1>*20, <liquid:creosote>*2000 , 0, <minecraft:log:1> * 16, null, 200, 64);
0- circuit number
null - input fluid
