### ISSUE TITLE
how to remove recipes?

### ISSUE THREAD

**Issue by apk-modpack** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#57]
I'm trying to disable a specific recipe to replace it with another one, but when I put the energy at 0 in the Gregtech/Recipes config file and add a script to replace, it doesn't appear. The recipe is the same (energy consumption, duration, ....) but I changed one item. What could be wrong?

**Comment by Glease** [comment]
Use a slightly different EU/t, e.g. change 120 into 119 or something.

**Comment by apk-modpack** [comment]
ok, I tried it and it worked. thank you!
