### ISSUE TITLE
Expand item input limit in mixer recipes to 9 from 4

### ISSUE THREAD

**Issue by C0bra5** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#58]
I was trying to backport some of the oreporc changes to 2.3.0. That's when I discovered that the mixer addrecipe function has a limit of 4 item inputs. Considering the single block mixers can have up to 9 item inputs, I believe the limit should be pushed to 9 or removed entirely.

relevant files:
https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon/blob/febda0e1bfe20caf44f7b930a60d3c6799048b5a/src/main/java/gttweaker/mods/gregtech/machines/Mixer.java

**Comment by Dream-Master** [comment]
change stuff in code make much more sense. We slowly remove scripts and add them to code
