### ISSUE TITLE
Question: Bronze Age machines.

### ISSUE THREAD

**Issue by wujekbrezniew** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#9]
Are scripts work with GT Bronze Age machines ?
If, not, Is it possible to add ?

**Comment by Dream-Master** [comment]
No they not working and i havn't a clue how to add them. sorry.

**Comment by Techlone** [comment]
@Dream-Master
No, it's not. GTTweaker add recipes to global recipe list for each machine type.
I think bronze machines take recipes of first tier (32< EU/tick) for itself. I not sure that it's true but it works for me.

**Comment by Dream-Master** [comment]
@Techlone 
Ok you right the Bronze Machines like Alloy smelter, E-Furnace and Marerator etc works with 32<EU reipe.
The Bronze Blast Furnace is different.

**Comment by Techlone** [comment]
Oh, yes, the Bronze Blast Furnace...
Its recipes are hardcoded. I checked this some time ago and it upset me.

**Comment by Dream-Master** [comment]
No problem for me and my Modpack I used a modded gt version so i change what i want to change;)

**Comment by Dream-Master** [comment]
Ok close it now.
